In [1]:
from __future__ import print_function
import os
data_path = ['data']

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

filepath = os.sep.join(data_path + ['Ames_Housing_Sales.csv'])
data = pd.read_csv(filepath)
data.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,...,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold,SalePrice
0,856.0,854.0,0.0,None,3,1Fam,TA,No,706.0,0.0,...,0.0,Pave,8,856.0,AllPub,0.0,2003,2003,2008,208500.0
1,1262.0,0.0,0.0,None,3,1Fam,TA,Gd,978.0,0.0,...,0.0,Pave,6,1262.0,AllPub,298.0,1976,1976,2007,181500.0
2,920.0,866.0,0.0,None,3,1Fam,TA,Mn,486.0,0.0,...,0.0,Pave,6,920.0,AllPub,0.0,2001,2002,2008,223500.0
3,961.0,756.0,0.0,None,3,1Fam,Gd,No,216.0,0.0,...,0.0,Pave,7,756.0,AllPub,0.0,1915,1970,2006,140000.0
4,1145.0,1053.0,0.0,None,4,1Fam,TA,Av,655.0,0.0,...,0.0,Pave,9,1145.0,AllPub,192.0,2000,2000,2008,250000.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1379 entries, 0 to 1378
Data columns (total 80 columns):
1stFlrSF         1379 non-null float64
2ndFlrSF         1379 non-null float64
3SsnPorch        1379 non-null float64
Alley            1379 non-null object
BedroomAbvGr     1379 non-null int64
BldgType         1379 non-null object
BsmtCond         1379 non-null object
BsmtExposure     1379 non-null object
BsmtFinSF1       1379 non-null float64
BsmtFinSF2       1379 non-null float64
BsmtFinType1     1379 non-null object
BsmtFinType2     1379 non-null object
BsmtFullBath     1379 non-null int64
BsmtHalfBath     1379 non-null int64
BsmtQual         1379 non-null object
BsmtUnfSF        1379 non-null float64
CentralAir       1379 non-null object
Condition1       1379 non-null object
Condition2       1379 non-null object
Electrical       1379 non-null object
EnclosedPorch    1379 non-null float64
ExterCond        1379 non-null object
ExterQual        1379 non-null object
Exterior1st      1379 non-null object
Exterior2nd      1379 non-null object
Fence            1379 non-null object
FireplaceQu      1379 non-null object
Fireplaces       1379 non-null int64
Foundation       1379 non-null object
FullBath         1379 non-null int64
Functional       1379 non-null object
GarageArea       1379 non-null float64
GarageCars       1379 non-null int64
GarageCond       1379 non-null object
GarageFinish     1379 non-null object
GarageQual       1379 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GrLivArea        1379 non-null float64
HalfBath         1379 non-null int64
Heating          1379 non-null object
HeatingQC        1379 non-null object
HouseStyle       1379 non-null object
KitchenAbvGr     1379 non-null int64
KitchenQual      1379 non-null object
LandContour      1379 non-null object
LandSlope        1379 non-null object
LotArea          1379 non-null float64
LotConfig        1379 non-null object
LotFrontage      1379 non-null float64
LotShape         1379 non-null object
LowQualFinSF     1379 non-null float64
MSSubClass       1379 non-null int64
MSZoning         1379 non-null object
MasVnrArea       1379 non-null float64
MasVnrType       1379 non-null object
MiscFeature      1379 non-null object
MiscVal          1379 non-null float64
MoSold           1379 non-null int64
Neighborhood     1379 non-null object
OpenPorchSF      1379 non-null float64
OverallCond      1379 non-null int64
OverallQual      1379 non-null int64
PavedDrive       1379 non-null object
PoolArea         1379 non-null float64
PoolQC           1379 non-null object
RoofMatl         1379 non-null object
RoofStyle        1379 non-null object
SaleCondition    1379 non-null object
SaleType         1379 non-null object
ScreenPorch      1379 non-null float64
Street           1379 non-null object
TotRmsAbvGrd     1379 non-null int64
TotalBsmtSF      1379 non-null float64
Utilities        1379 non-null object
WoodDeckSF       1379 non-null float64
YearBuilt        1379 non-null int64
YearRemodAdd     1379 non-null int64
YrSold           1379 non-null int64
SalePrice        1379 non-null float64
dtypes: float64(21), int64(16), object(43)
memory usage: 862.0+ KB

In [4]:
data.describe()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,EnclosedPorch,...,OverallQual,PoolArea,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold,SalePrice
count,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,...,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.00000
mean,1177.129804,353.424946,3.609862,2.865120,455.578680,48.102248,0.430747,0.058738,570.765047,21.039159,...,6.187092,2.920957,15.945613,6.552574,1074.445975,97.456853,1972.958666,1985.435098,2007.812183,185479.51124
std,387.014961,439.553171,30.154682,0.783961,459.691379,164.324665,0.514052,0.238285,443.677845,60.535107,...,1.345780,41.335545,57.249593,1.589821,436.371874,126.699192,29.379883,20.444852,1.330221,79023.89060
min,438.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1880.000000,1950.000000,2006.000000,35311.00000
25%,894.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,228.000000,0.000000,...,5.000000,0.000000,0.000000,5.000000,810.000000,0.000000,1955.000000,1968.000000,2007.000000,134000.00000
50%,1098.000000,0.000000,0.000000,3.000000,400.000000,0.000000,0.000000,0.000000,476.000000,0.000000,...,6.000000,0.000000,0.000000,6.000000,1008.000000,0.000000,1976.000000,1994.000000,2008.000000,167500.00000
75%,1414.000000,738.500000,0.000000,3.000000,732.000000,0.000000,1.000000,0.000000,811.000000,0.000000,...,7.000000,0.000000,0.000000,7.000000,1314.000000,171.000000,2001.000000,2004.000000,2009.000000,217750.00000
max,4692.000000,2065.000000,508.000000,6.000000,5644.000000,1474.000000,2.000000,2.000000,2336.000000,552.000000,...,10.000000,738.000000,480.000000,12.000000,6110.000000,857.000000,2010.000000,2010.000000,2010.000000,755000.00000

In [5]:
data.describe(include=[np.number], percentiles=[.5]).transpose().drop("count", axis=1)

                        mean           std      min       50%            max
1stFlrSF         1177.129804    387.014961    438.0    1098.0    4692.000000
2ndFlrSF          353.424946    439.553171      0.0       0.0    2065.000000
3SsnPorch           3.609862     30.154682      0.0       0.0     508.000000
BedroomAbvGr        2.865120      0.783961      0.0       3.0       6.000000
BsmtFinSF1        455.578680    459.691379      0.0     400.0    5644.000000
BsmtFinSF2         48.102248    164.324665      0.0       0.0    1474.000000
BsmtFullBath        0.430747      0.514052      0.0       0.0       2.000000
BsmtHalfBath        0.058738      0.238285      0.0       0.0       2.000000
BsmtUnfSF         570.765047    443.677845      0.0     476.0    2336.000000
EnclosedPorch      21.039159     60.535107      0.0       0.0     552.000000
Fireplaces          0.641769      0.645985      0.0       1.0       3.000000
FullBath            1.580131      0.548051      0.0       2.0       3.000000
GarageArea        500.762146    185.680520    160.0     484.0    1418.000000
GarageCars          1.870921      0.630055      1.0       2.0       4.000000
GarageYrBlt      1978.506164     24.689725   1900.0    1980.0    2010.000000
GrLivArea        1534.689630    519.140514    438.0    1479.0    5642.000000
HalfBath            0.395939      0.502402      0.0       0.0       2.000000
KitchenAbvGr        1.038434      0.196048      1.0       1.0       3.000000
LotArea         10695.812183  10214.702133   1300.0    9591.0  215245.000000
LotFrontage        75.112314     28.214221     21.0      71.0     405.783193
LowQualFinSF        4.134880     40.130546      0.0       0.0     572.000000
MSSubClass         56.022480     41.026897     20.0      50.0     190.000000
MasVnrArea        108.364757    184.195220      0.0       0.0    1600.000000
MiscVal            42.889050    501.613931      0.0       0.0   15500.000000
MoSold              6.334300      2.696674      1.0       6.0      12.000000
OpenPorchSF        47.276287     65.210465      0.0      27.0     547.000000
OverallCond         5.577955      1.081031      2.0       5.0       9.000000
OverallQual         6.187092      1.345780      2.0       6.0      10.000000
PoolArea            2.920957     41.335545      0.0       0.0     738.000000
ScreenPorch        15.945613     57.249593      0.0       0.0     480.000000
TotRmsAbvGrd        6.552574      1.589821      3.0       6.0      12.000000
TotalBsmtSF      1074.445975    436.371874      0.0    1008.0    6110.000000
WoodDeckSF         97.456853    126.699192      0.0       0.0     857.000000
YearBuilt        1972.958666     29.379883   1880.0    1976.0    2010.000000
YearRemodAdd     1985.435098     20.444852   1950.0    1994.0    2010.000000
YrSold           2007.812183      1.330221   2006.0    2008.0    2010.000000
SalePrice      185479.511240  79023.890600  35311.0  167500.0  755000.000000

In [6]:
data.describe(include=[np.object]).transpose().drop("count", axis=1)

              unique      top  freq
Alley              3     None  1297
BldgType           5     1Fam  1166
BsmtCond           4       TA   889
BsmtExposure       5       No   582
BsmtFinType1       6     None   426
BsmtFinType2       7      Unf   790
BsmtQual           5       TA   442
CentralAir         2        Y  1310
Condition1         9     Norm  1195
Condition2         8     Norm  1365
Electrical         5    SBrkr  1273
ExterCond          4       TA  1221
ExterQual          4       TA   833
Exterior1st       14  VinylSd   498
Exterior2nd       16  VinylSd   487
Fence              5     None  1114
FireplaceQu        6     None   618
Foundation         6    PConc   633
Functional         7      Typ  1287
GarageCond         5       TA  1326
GarageFinish       3      Unf   605
GarageQual         5       TA  1311
GarageType         6   Attchd   870
Heating            6     GasA  1353
HeatingQC          5       Ex   720
HouseStyle         8   1Story   686
KitchenQual        4       TA   676
LandContour        4      Lvl  1244
LandSlope          3      Gtl  1306
LotConfig          5   Inside   988
LotShape           4      Reg   861
MSZoning           5       RL  1101
MasVnrType         4     None   797
MiscFeature        5     None  1328
Neighborhood      25    NAmes   219
PavedDrive         3        Y  1293
PoolQC             4     None  1372
RoofMatl           8  CompShg  1354
RoofStyle          6    Gable  1070
SaleCondition      6   Normal  1137
SaleType           9       WD  1194
Street             2     Pave  1374
Utilities          2   AllPub  1378

### Data Cleaning

In [7]:
col = data.dtypes != np.object
check = data.columns[col]
# convert 0 value to average
for i in range(len(check)): 
    data[check[i]] = data[check[i]].apply(lambda x: np.nan if x == 0 else x)

In [8]:
x_data = data.drop('SalePrice', axis=1)
y_data = data['SalePrice']

In [9]:
data[check[1]] = data[check[1]].apply(lambda x: np.nan if x == 0 else x)

In [10]:
# Select the object (string) columns
mask = data.dtypes == np.object
categorical_cols = data.columns[mask]

In [11]:
categorical_cols

Index(['Alley', 'BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'BsmtQual', 'CentralAir', 'Condition1', 'Condition2',
       'Electrical', 'ExterCond', 'ExterQual', 'Exterior1st', 'Exterior2nd',
       'Fence', 'FireplaceQu', 'Foundation', 'Functional', 'GarageCond',
       'GarageFinish', 'GarageQual', 'GarageType', 'Heating', 'HeatingQC',
       'HouseStyle', 'KitchenQual', 'LandContour', 'LandSlope', 'LotConfig',
       'LotShape', 'MSZoning', 'MasVnrType', 'MiscFeature', 'Neighborhood',
       'PavedDrive', 'PoolQC', 'RoofMatl', 'RoofStyle', 'SaleCondition',
       'SaleType', 'Street', 'Utilities'],
      dtype='object')

In [12]:
data[categorical_cols[1]]

0       1Fam
1       1Fam
2       1Fam
3       1Fam
4       1Fam
        ...
1374    1Fam
1375    1Fam
1376    1Fam
1377    1Fam
1378    1Fam
Name: BldgType, Length: 1379, dtype: object

In [13]:
num_ohc_cols = (data[categorical_cols]
                .apply(lambda x: x.nunique())
                .sort_values(ascending=False))

from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Copy of the data
data_ohc = data.copy()

# The encoders
le = LabelEncoder()
ohc = OneHotEncoder()

for col in num_ohc_cols.index:
    
    # Integer encode the string categories
    dat = le.fit_transform(data_ohc[col]).astype(np.int)
    
    # Remove the original column from the dataframe
    data_ohc = data_ohc.drop(col, axis=1)

    # One hot encode the data--this returns a sparse array
    new_dat = ohc.fit_transform(dat.reshape(-1,1))

    # Create unique column names
    n_cols = new_dat.shape[1]
    col_names = ['_'.join([col, str(x)]) for x in range(n_cols)]

    # Create the new dataframe
    new_df = pd.DataFrame(new_dat.toarray(), 
                          index=data_ohc.index, 
                          columns=col_names)

    # Append the new data to the dataframe
    data_ohc = pd.concat([data_ohc, new_df], axis=1)

In [14]:
data_ohc.shape

(1379, 295)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le1 = LabelEncoder()
for i in range(len(categorical_cols)):
    data[categorical_cols[i]] = le1.fit_transform(data[categorical_cols[i]])

In [17]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3, weights="uniform")
data_ = imputer.fit_transform(data_ohc)

data_ x데이터 , y_data - 타겟

In [18]:
# Getting the number of missing values in each column
num_missing = data.isna().sum()
# Excluding columns that contains 0 missing values
num_missing = num_missing[num_missing > 0]
# Getting the percentages of missing values
percent_missing = num_missing * 100 / data.shape[0]
# Concatenating the number and perecentage of missing values 
# into one dataframe and sorting it
pd.concat([num_missing, percent_missing], axis=1, 
          keys=['Missing Values', 'Percentage']).\
          sort_values(by="Missing Values", ascending=False)

               Missing Values  Percentage
PoolArea                 1372   99.492386
LowQualFinSF             1360   98.622190
3SsnPorch                1355   98.259608
MiscVal                  1330   96.446701
BsmtHalfBath             1299   94.198695
ScreenPorch              1263   91.588107
BsmtFinSF2               1216   88.179840
EnclosedPorch            1193   86.511965
HalfBath                  842   61.058738
BsmtFullBath              798   57.868020
MasVnrArea                794   57.577955
2ndFlrSF                  777   56.345178
WoodDeckSF                701   50.833938
Fireplaces                618   44.815083
OpenPorchSF               601   43.582306
BsmtFinSF1                426   30.891951
BsmtUnfSF                 103    7.469181
TotalBsmtSF                30    2.175489
FullBath                    8    0.580131
BedroomAbvGr                6    0.435098

-> Missing Value 없음

### Feature Encoding Test

In [19]:
test = data

In [20]:
# Select the object (string) columns
mask = data.dtypes == np.object
categorical_cols = data.columns[mask]

from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
for i in range(len(categorical_cols)):
    test[categorical_cols[i]] = le1.fit_transform(test[categorical_cols[i]])

In [21]:
#test.drop(['Alley', 'CentralAir', 'Condition2', 'Electrical', 'ExterCond', 'Functional', 'GarageCond', 'GarageQual', 'Heating', 'LandContour', 'LandSlope', 'MiscFeature', 'PavedDrive', 'PoolQC', 'RoofMatl', 'Street', 'Utilities'], 1, inplace=True)

In [22]:
x_data = data.drop('SalePrice', axis=1)
y_data = data['SalePrice']

In [23]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3, weights="uniform")
x_data = imputer.fit_transform(x_data)

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_, y_data, test_size = 0.20, random_state = 123)

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test, y_test)))

훈련 세트 점수: 1.000
테스트 세트 점수: 1.000

### Feature Engineering 사용

In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_data_sts = scaler.fit_transform(x_data)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data_sts, y_data, test_size = 0.20, random_state = 123)

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test, y_test)))

훈련 세트 점수: 0.857
테스트 세트 점수: 0.778

In [27]:
data

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,...,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold,SalePrice
0,856.0,854.0,NaN,1,3.0,0,3,3,706.0,NaN,...,NaN,1,8,856.0,0,NaN,2003,2003,2008,208500.0
1,1262.0,NaN,NaN,1,3.0,0,3,1,978.0,NaN,...,NaN,1,6,1262.0,0,298.0,1976,1976,2007,181500.0
2,920.0,866.0,NaN,1,3.0,0,3,2,486.0,NaN,...,NaN,1,6,920.0,0,NaN,2001,2002,2008,223500.0
3,961.0,756.0,NaN,1,3.0,0,1,3,216.0,NaN,...,NaN,1,7,756.0,0,NaN,1915,1970,2006,140000.0
4,1145.0,1053.0,NaN,1,4.0,0,3,0,655.0,NaN,...,NaN,1,9,1145.0,0,192.0,2000,2000,2008,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,953.0,694.0,NaN,1,3.0,0,2,4,NaN,NaN,...,NaN,1,7,953.0,0,NaN,1999,2000,2007,175000.0
1375,2073.0,NaN,NaN,1,3.0,0,3,3,790.0,163.0,...,NaN,1,7,1542.0,0,349.0,1978,1988,2010,210000.0
1376,1188.0,1152.0,NaN,1,4.0,0,1,3,275.0,NaN,...,NaN,1,9,1152.0,0,NaN,1941,2006,2010,266500.0
1377,1078.0,NaN,NaN,1,2.0,0,3,2,49.0,1029.0,...,NaN,1,5,1078.0,0,366.0,1950,1996,2010,142125.0
1378,1256.0,NaN,NaN,1,3.0,0,3,3,830.0,290.0,...,NaN,1,6,1256.0,0,736.0,1965,1965,2008,147500.0

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_data_mms = scaler.fit_transform(x_data)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data_mms, y_data, test_size = 0.20, random_state = 123)

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test, y_test)))

훈련 세트 점수: 0.857
테스트 세트 점수: 0.778

### 특성 자동 선택

In [30]:
from sklearn.feature_selection import SelectPercentile

select = SelectPercentile(percentile=60) # 60프로 선택
select.fit(x_data_mms, y_data)    # 초기 데이터로 특성 선택
X_train_selected = select.transform(X_train)
X_test_selected = select.transform(X_test)

model = linear_model.LinearRegression()
model.fit(X_train_selected, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train_selected, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test_selected, y_test)))

훈련 세트 점수: 0.837
테스트 세트 점수: 0.800

### 교차 검증

In [31]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn import linear_model

model = linear_model.LinearRegression()
kfold = KFold(n_splits=5, shuffle=True, random_state=0)
print("교차 검증 점수:\n{}".format(cross_val_score(model, x_data_mms, y_data, cv=kfold)))

교차 검증 점수:
[0.83798369 0.85604099 0.80132519 0.67014084 0.81662884]

In [32]:
data.describe(include=[np.number], percentiles=[.5]).transpose().drop("count", axis=1)

                       mean           std      min       50%       max
1stFlrSF        1177.129804    387.014961    438.0    1098.0    4692.0
2ndFlrSF         809.589701    270.320103    167.0     780.0    2065.0
3SsnPorch        207.416667    101.825049     23.0     180.0     508.0
Alley              0.997099      0.243922      0.0       1.0       2.0
BedroomAbvGr       2.877640      0.762383      1.0       3.0       6.0
...                     ...           ...      ...       ...       ...
WoodDeckSF       198.219764    112.568838     12.0     172.5     857.0
YearBuilt       1972.958666     29.379883   1880.0    1976.0    2010.0
YearRemodAdd    1985.435098     20.444852   1950.0    1994.0    2010.0
YrSold          2007.812183      1.330221   2006.0    2008.0    2010.0
SalePrice     185479.511240  79023.890600  35311.0  167500.0  755000.0

[80 rows x 5 columns]

In [33]:
data['2ndFlrSF']

0        854.0
1          NaN
2        866.0
3        756.0
4       1053.0
         ...
1374     694.0
1375       NaN
1376    1152.0
1377       NaN
1378       NaN
Name: 2ndFlrSF, Length: 1379, dtype: float64

In [34]:
## 최종 모델링
y_data_log = np.log1p(y_data)

X_train, X_test, y_train, y_test = train_test_split(x_data_mms, y_data_log, test_size = 0.25, random_state = 0)

from sklearn.feature_selection import SelectPercentile

select = SelectPercentile(percentile=60) # 60프로 선택
select.fit(x_data_mms, y_data_log)    # 초기 데이터로 특성 선택
X_train_selected = select.transform(X_train)
X_test_selected = select.transform(X_test)

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train_selected, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train_selected, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test_selected, y_test)))

훈련 세트 점수: 0.856
테스트 세트 점수: 0.873

In [35]:
x_data.shape

(1379, 79)

In [36]:
data_.shape

(1379, 295)

### 최근 모델링(data_ 이용)

In [37]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_data_mms = scaler.fit_transform(data_)

from sklearn.decomposition import PCA
# 데이터의 처음 두 개의 주성분만 유지합니다.
pca = PCA(n_components=150)
# 유방암 데이터로 PCA 모델을 만듭니다.
x_pca = pca.fit_transform(x_data_mms)

In [38]:
x_pca.shape

(1379, 150)

In [39]:
y_data_log = np.log1p(y_data)

X_train, X_test, y_train, y_test = train_test_split(x_pca, y_data_log, test_size = 0.10, random_state=42)


from sklearn.feature_selection import SelectPercentile

# select = SelectPercentile(percentile=100) # 60프로 선택
# select.fit(x_data, y_data_log)    # 초기 데이터로 특성 선택
# X_train_selected = select.transform(X_train)
# X_test_selected = select.transform(X_test)

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test, y_test)))

훈련 세트 점수: 0.927
테스트 세트 점수: 0.892

In [40]:
from sklearn.metrics import mean_squared_error
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)    
pred = model.predict(X_test)
y_pred = np.expm1(pred)
y_true = np.expm1(list(y_test))
#mean_squared_error(y_data, y_pred)  

# Root mean squared error
mse = mean_squared_error(y_true, y_pred)  
rmse = np.sqrt(mse)
rmse

24929.103316862867

In [41]:
## 최종 모델링
y_data_log = np.log1p(y_data)

X_train, X_test, y_train, y_test = train_test_split(x_data_mms, y_data_log, test_size = 0.15)

from sklearn.feature_selection import SelectPercentile

select = SelectPercentile(percentile=60) # 60프로 선택
select.fit(x_data_mms, y_data_log)    # 초기 데이터로 특성 선택
X_train_selected = select.transform(X_train)
X_test_selected = select.transform(X_test)

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train_selected, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train_selected, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test_selected, y_test)))

훈련 세트 점수: 0.978
테스트 세트 점수: -1682906206507853.250

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw

In [42]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
model = linear_model.LinearRegression()
model.fit(X_train_selected, y_train)
pred = model.predict(X_test_selected)
y_pred = np.expm1(pred)
y_true = np.expm1(list(y_test))
#mean_squared_error(y_data, y_pred)  

# Root mean squared error
mse = mean_squared_error(y_true, y_pred)  
rmse = np.sqrt(mse)
rmse

95108.78811622054

In [43]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
#Validation function
n_folds = 10

def rmsle_cv(model):
    kf = KFold(n_folds, shuffle=True)#.get_n_splits(x_data_mms)
    rmse = np.sqrt(-cross_val_score(model, x_pca, y_data, scoring="neg_mean_squared_error", cv = kf))
    return(rmse)
m = 0;
for i in rmsle_cv(model):
    m = m + i;
m / 10

28565.658609763796

In [44]:
kfold = KFold(n_splits=5, shuffle=True)
print("교차 검증 점수:\n{}".format(cross_val_score(model, x_pca, y_data, cv=kfold)))

교차 검증 점수:
[0.88234973 0.88603483 0.87462061 0.77509193 0.85411416]

## 테스트

In [45]:
#x_data.drop(['Alley', 'CentralAir', 'Condition2', 'Electrical', 'ExterCond', 'Functional', 'GarageCond', 'GarageQual', 'Heating', 'LandContour', 'LandSlope', 'MiscFeature', 'PavedDrive', 'PoolQC', 'RoofMatl', 'Street', 'Utilities'], 1, inplace=True)

In [46]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_data_mms = scaler.fit_transform(x_data)

In [47]:
## 최종 모델링
y_data_log = np.log1p(y_data)

X_train, X_test, y_train, y_test = train_test_split(x_data_mms, y_data_log, test_size = 0.20, random_state = 123)

from sklearn.feature_selection import SelectPercentile

select = SelectPercentile(percentile=60) # 60프로 선택
select.fit(x_data_mms, y_data_log)    # 초기 데이터로 특성 선택
X_train_selected = select.transform(X_train)
X_test_selected = select.transform(X_test)

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train_selected, y_train)     

print("훈련 세트 점수: {:.3f}".format(model.score(X_train_selected, y_train)))
print("테스트 세트 점수: {:.3f}".format(model.score(X_test_selected, y_test)))

훈련 세트 점수: 0.860
테스트 세트 점수: 0.862

In [48]:
from sklearn.metrics import mean_squared_error
model = linear_model.LinearRegression()
model.fit(X_train_selected, y_train)
pred = model.predict(X_test_selected)
y_pred = np.expm1(pred)
y_true = np.expm1(list(y_test))
#mean_squared_error(y_data, y_pred)  

# Root mean squared error
mse = mean_squared_error(y_true, y_pred)  
rmse = np.sqrt(mse)
rmse

30371.126972076065